// Adding libraries
using UnityEngine;
using UnityEngine.InputSystem;

// Class for our input manager
public class InputManager : MonoBehaviour {
    private PlayerInput playerInput;
    private PlayerInput.GamePlayActions gamePlayMap;
    private PlayerController controller;

    // Init the C# Class generated by Input Actions
    void Awake() {
	playerInput = new PlayerInput();
	gamePlayMap = playerInput.GamePlay;
	controller = GetComponent<PlayerController>();

	// Bind One shot actions
	// This is the Binding style i used in my COD Zombies game
	gamePlayMap.Shoot.started += ctx => controller.StartCharging();
        gamePlayMap.Shoot.canceled += ctx => controller.ReleaseShot();

	// Same method as shooting we are going to do Sprinting
	// This is because I want to have it on a 'Hold Button' system
	gamePlayMap.Sprint.started += ctx => controller.Sprinting(true);
        gamePlayMap.Sprint.canceled += ctx => controller.Sprinting(false);
	
    }

    // Continuous Movement for the player
    void FixedUpdate() {
	controller.ProcessMove(gamePlayMap.Move.ReadValue<Vector2>());
    }

    private void OnEnable() {
        gamePlayMap.Enable();
    }
	
    private void OnDisable() {
        gamePlayMap.Disable();
    }
}
