// Adding libraries
using UnityEngine;
using UnityEngine.InputSystem;

// Class for our input manager
public class InputManager : MonoBehaviour {
    private PlayerInput playerInput;
    private PlayerInput.GamePlayActions gamePlayMap;
    // private PlayerController controller;

    [Header("Reference")]
    public PlayerSwitcher playerSwitcher;
    
    // Init the C# Class generated by Input Actions
    void Awake() {
	playerInput = new PlayerInput();
	gamePlayMap = playerInput.GamePlay;
	
	// Bind One shot actions
	// This is the Binding style i used in my COD Zombies game
	gamePlayMap.Shoot.started += ctx => playerSwitcher.ActivePlayer?.StartCharging();
        gamePlayMap.Shoot.canceled += ctx => playerSwitcher.ActivePlayer?.ReleaseShot();

	// eventually implement Charge pass
	gamePlayMap.Pass.performed += ctx => playerSwitcher.ActivePlayer?.PassBall();
	
	// Same method as shooting we are going to do Sprinting
	// This is because I want to have it on a 'Hold Button' system
	gamePlayMap.Sprint.started += ctx => playerSwitcher.ActivePlayer?.Sprinting(true);
        gamePlayMap.Sprint.canceled += ctx => playerSwitcher.ActivePlayer?.Sprinting(false);

	// Adding SkillMoves to the game
	// Using performed because we dont hold in a key or button to perform the event
	gamePlayMap.Skill.performed += ctx => playerSwitcher.ActivePlayer?.StepOver();

	// Adding Celebrations for the game
	gamePlayMap.Sui_Celebration.performed += ctx => playerSwitcher.ActivePlayer?.PlaySuiCelebration();
    }

    // Continuous Movement for the player
    void FixedUpdate() {
	playerSwitcher.ActivePlayer?.ProcessMove(gamePlayMap.Move.ReadValue<Vector2>());
    }

    private void OnEnable() {
        gamePlayMap.Enable();
    }
	
    private void OnDisable() {
        gamePlayMap.Disable();
    }
}
