// Adding libraries
using UnityEngine;
using UnityEngine.InputSystem;

// Class for our input manager
public class InputManager : MonoBehaviour {
    private PlayerInput playerInput;
    private PlayerInput.GamePlayActions gamePlayMap;
    private PlayerController controller;

    // Init the C# Class generated by Input Actions
    void Awake() {
	playerInput = new PlayerInput();
	gamePlayMap = playerInput.GamePlay;
	controller = GetComponent<PlayerController>();

	// Bind One shot actions
	// This is the Binding style i used in my COD Zombies game
	gamePlayMap.Shoot.started += ctx => controller.StartCharging();
        gamePlayMap.Shoot.canceled += ctx => controller.ReleaseShot();
	
       	// Gameplay.Pass.performed += ctx => controller.Pass();
	// Gameplay.Sprint.performed += ctx => controller.Sprint();
    }

    // Continuous Movement for the player
    void FixedUpdate() {
	controller.ProcessMove(gamePlayMap.Move.ReadValue<Vector2>());
    }

    private void OnEnable() {
        gamePlayMap.Enable();
    }
	
    private void OnDisable() {
        gamePlayMap.Disable();
    }
}
